[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 